WITH ECOLI_RANK AS (
    SELECT ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS QUARTILE
    FROM ECOLI_DATA
)

SELECT ID,
    CASE QUARTILE
        WHEN 1 THEN 'CRITICAL'
        WHEN 2 THEN 'HIGH'
        WHEN 3 THEN 'MEDIUM'
        WHEN 4 THEN 'LOW'
    END AS COLONY_NAME
FROM ECOLI_RANK
ORDER BY ID ASC;