WITH E2 AS (SELECT MAX(SIZE_OF_COLONY) SIZE, YEAR(DIFFERENTIATION_DATE) YEAR
                  FROM ECOLI_DATA
                  GROUP BY YEAR(DIFFERENTIATION_DATE))

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, E2.SIZE - SIZE_OF_COLONY YEAR_DEV, ID
FROM ECOLI_DATA
JOIN E2
ON YEAR(DIFFERENTIATION_DATE) = E2.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC